CREATE TABLE IF NOT EXISTS customers (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS phonenumber (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  number VARCHAR (255),
  description VARCHAR (255),
  type VARCHAR (255)
);

